version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: cloud/docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./freshness.db:/app/freshness.db
      - ./ml/models:/app/ml/models
      - ./app/static/uploads:/app/app/static/uploads
    environment:
      - FLASK_ENV=production
